import React, { useState } from 'react';
import api from '../api';

// ============================================================
// INSIGHT ITEM
// ============================================================
function InsightItem({ icon, title, body, type = 'info' }) {
  const colorMap = {
    info: '#60a5fa',
    warning: '#fbbf24',
    success: '#34d399',
    danger: '#f87171',
    purple: '#a78bfa'
  };

  return (
    <div className="insight-card">
      <div className="insight-header" style={{ color: colorMap[type] }}>
        <span>{icon}</span>
        {title}
      </div>
      <div className="insight-body">{body}</div>
    </div>
  );
}

// ============================================================
// SKILLS PANEL
// ============================================================
function SkillGapPanel({ currentSkills, skillsToAdd }) {
  return (
    <div>
      <div style={{ marginBottom: 12 }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
          Current Skills
        </div>
        <div className="skill-tags">
          {currentSkills.map(s => <span key={s} className="skill-tag">{s}</span>)}
          {currentSkills.length === 0 && <span className="text-muted text-sm">No skills detected</span>}
        </div>
      </div>
      {skillsToAdd?.length > 0 && (
        <div>
          <div style={{ fontSize: 12, fontWeight: 600, color: '#10b981', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Skills to Add 🎯
          </div>
          <div className="skill-tags">
            {skillsToAdd.map(s => (
              <span key={s} style={{
                padding: '4px 12px',
                background: 'rgba(16,185,129,0.1)',
                border: '1px solid rgba(16,185,129,0.3)',
                borderRadius: 999, fontSize: 12, fontWeight: 500,
                color: '#34d399'
              }}>{s} ✨</span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ============================================================
// MAIN INSIGHTS PANEL
// ============================================================
export default function InsightsPanel({ studentData, simulation }) {
  const [simulateInput, setSimulateInput] = useState({ skills: '', goal: 'SDE' });
  const [simResult, setSimResult] = useState(simulation || null);
  const [simLoading, setSimLoading] = useState(false);
  const [error, setError] = useState('');

  const GOALS = ['SDE', 'Data Analyst', 'Full Stack Developer', 'Data Scientist', 'Product Manager'];

  const handleSimulate = async () => {
    const skills = simulateInput.skills
      .split(',')
      .map(s => s.trim().toLowerCase())
      .filter(Boolean);

    if (skills.length === 0) {
      setError('Please enter at least one skill.');
      return;
    }
    setError('');
    setSimLoading(true);
    try {
      const result = await api.simulate(skills, simulateInput.goal, 5, 1);
      setSimResult(result);
    } catch (e) {
      setError('Simulation failed. Make sure backend is running.');
    } finally {
      setSimLoading(false);
    }
  };

  // Use student data if provided, else standalone panel
  const currentSkills = studentData?.skills || [];
  const alerts = studentData?.alerts || [];
  const suggestions = studentData?.suggestions || [];
  const strategy = studentData?.strategy || '';
  const alternatives = studentData?.alternative_careers || [];
  const status = studentData?.status;

  return (
    <div>
      <div className="section-header">
        <div className="section-title">🤖 AI Insights Panel</div>
        <div className="section-subtitle">
          Autonomous recommendations generated by PrepGenie Agents.
        </div>
      </div>

      <div className="grid-2">
        {/* LEFT: CURRENT STUDENT INSIGHTS */}
        <div>
          {/* STATUS BASED INSIGHTS */}
          {status && (
            <div className="card mb-16">
              <div className="card-title">
                <span className="icon">🎯</span>
                Current Status Analysis
              </div>
              {status === 'At Risk' && (
                <InsightItem
                  icon="🚨"
                  title="Immediate Action Needed"
                  body="Your placement probability is critically low. Focus on completing daily tasks and reducing missed sessions. The Decision Agent has flagged your profile for urgent review."
                  type="danger"
                />
              )}
              {status === 'Learning' && (
                <InsightItem
                  icon="📈"
                  title="Progress On Track"
                  body="You're progressing steadily. Stay consistent with your daily tasks. The AI recommends pushing your weak skill areas this week to cross the 70% threshold."
                  type="info"
                />
              )}
              {status === 'Ready' && (
                <InsightItem
                  icon="🎉"
                  title="Job Ready!"
                  body="Excellent work! Your profile is job-ready. The Decision Agent recommends starting applications at top companies and scheduling mock interviews this week."
                  type="success"
                />
              )}
            </div>
          )}

          {/* ALERTS */}
          {alerts.length > 0 && (
            <div className="card mb-16">
              <div className="card-title">
                <span className="icon">⚠️</span>
                Active Alerts
              </div>
              {alerts.map((a, i) => (
                <div key={i} className="alert alert-warning">{a}</div>
              ))}
            </div>
          )}

          {/* AI SUGGESTIONS */}
          {suggestions.length > 0 && (
            <div className="card mb-16">
              <div className="card-title">
                <span className="icon">💡</span>
                AI Recommendations
              </div>
              {suggestions.map((s, i) => (
                <InsightItem
                  key={i} icon="🤖"
                  title={`Recommendation ${i + 1}`}
                  body={s} type="purple"
                />
              ))}
            </div>
          )}

          {/* CAREER STRATEGY */}
          {strategy && (
            <div className="card mb-16">
              <div className="card-title">
                <span className="icon">🗺️</span>
                Career Strategy
              </div>
              <div style={{ fontSize: 14, color: '#94a3b8', lineHeight: 1.7, marginBottom: 16 }}>
                {strategy}
              </div>

              {alternatives.length > 0 && (
                <div>
                  <div style={{ fontSize: 12, fontWeight: 600, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 10 }}>
                    Alternative Career Paths
                  </div>
                  {alternatives.slice(0, 2).map((alt, i) => (
                    <div key={i} className="insight-card">
                      <div className="insight-header" style={{ color: '#a78bfa' }}>
                        💼 {alt.role}
                      </div>
                      <div className="insight-body">{alt.description}</div>
                      {alt.companies && (
                        <div style={{ marginTop: 8, fontSize: 12, color: '#64748b' }}>
                          Target: {alt.companies.join(' · ')}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* SKILL ANALYSIS */}
          {currentSkills.length > 0 && (
            <div className="card">
              <div className="card-title">
                <span className="icon">🧠</span>
                Skill Profile
              </div>
              <SkillGapPanel
                currentSkills={currentSkills}
                skillsToAdd={simResult?.skills_to_add || []}
              />
            </div>
          )}

          {!studentData && !simResult && (
            <div className="card" style={{ textAlign: 'center', padding: '48px 24px' }}>
              <div style={{ fontSize: 64, marginBottom: 16 }}>🔍</div>
              <div style={{ fontWeight: 600, marginBottom: 8 }}>No insights yet</div>
              <div className="text-muted text-sm">
                Generate a study plan in the Student Dashboard or run a manual simulation below.
              </div>
            </div>
          )}
        </div>

        {/* RIGHT: STANDALONE SIMULATOR */}
        <div>
          <div className="card">
            <div className="card-title">
              <span className="icon">⚡</span>
              Manual Skill Simulator
            </div>
            <p className="text-muted text-sm mb-16">
              Enter any set of skills to simulate placement probability and see what to learn next.
            </p>

            <div className="form-group">
              <label>Skills (comma-separated)</label>
              <input
                type="text"
                placeholder="e.g. python, sql, react, git"
                value={simulateInput.skills}
                onChange={e => setSimulateInput(p => ({ ...p, skills: e.target.value }))}
              />
            </div>

            <div className="form-group">
              <label>Target Role</label>
              <select
                value={simulateInput.goal}
                onChange={e => setSimulateInput(p => ({ ...p, goal: e.target.value }))}
              >
                {GOALS.map(g => <option key={g} value={g}>{g}</option>)}
              </select>
            </div>

            {error && <div className="alert alert-error mb-16">{error}</div>}

            <button
              className="btn btn-primary btn-full"
              onClick={handleSimulate}
              disabled={simLoading}
            >
              {simLoading ? '⏳ Simulating...' : '⚡ Run AI Simulation'}
            </button>
          </div>

          {/* SIMULATION RESULTS */}
          {simResult && (
            <div className="card mt-16">
              <div className="card-title">
                <span className="icon">📊</span>
                Simulation Results
              </div>

              <div className="simulate-widget">
                <div className="simulate-box">
                  <div className="simulate-label">Before</div>
                  <div className="simulate-value before">{simResult.current_probability}%</div>
                </div>
                <div className="simulate-arrow">→</div>
                <div className="simulate-box">
                  <div className="simulate-label">After Upskilling</div>
                  <div className="simulate-value after">{simResult.improved_probability}%</div>
                </div>
              </div>

              {simResult.probability_gain > 0 && (
                <div className="alert alert-success mt-16">
                  <span>📈</span>
                  <span>+{simResult.probability_gain}% gain by learning: <strong>{simResult.skills_to_add.join(', ')}</strong></span>
                </div>
              )}

              {simResult.simulation_narrative && (
                <InsightItem
                  icon="🤖"
                  title="AI Analysis"
                  body={simResult.simulation_narrative}
                  type="purple"
                />
              )}

              <div className="mt-16">
                <SkillGapPanel
                  currentSkills={simResult.current_skills || []}
                  skillsToAdd={simResult.skills_to_add || []}
                />
              </div>
            </div>
          )}

          {/* GENERAL TIPS */}
          <div className="card mt-16">
            <div className="card-title">
              <span className="icon">📚</span>
              Placement Tips
            </div>
            <InsightItem
              icon="🔢"
              title="DSA First"
              body="85% of SDE interviews focus on DSA. Solve minimum 3 problems daily. Focus on patterns, not memorization."
              type="info"
            />
            <InsightItem
              icon="🏗️"
              title="Build Projects"
              body="2-3 solid projects on GitHub matter more than 10 average ones. Each project should solve a real problem."
              type="success"
            />
            <InsightItem
              icon="📝"
              title="Resume Rule"
              body="Keep resume to 1 page. Quantify achievements: 'Reduced load time by 40%' beats 'worked on performance'."
              type="purple"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
